# Generated by Django 4.0.2 on 2022-03-12 10:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('appointId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=15, null=True)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('service', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Confirm'), (2, 'Cancel'), (3, 'Pending')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='DateTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('fromTime', models.TimeField()),
                ('fromTo', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, choices=[('Dental', 'Dental'), ('ENT', 'ENT'), ('Nephro', 'Nephro')], default='Dental', max_length=20, null=True)),
                ('freq', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
